# This pipeline gets the source code, runs NPM tasks, packages and uploads a universal Artifact.

trigger:
- master

pool:
  name: test1
  vmImage: local1

steps:


- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- task: Npm@1
  inputs:
    command: 'install'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'SpiceApps'
    vstsFeedPackagePublish: 'weightapp-artifact'
    versionOption: 'patch'
    packagePublishDescription: 'publish to Azure Artifacts'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName:
    itemPattern: '**/*'
    targetPath: '$(Build.SourcesDirectory)/weightapp2'